import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import { faGithub, faXTwitter } from '@fortawesome/free-brands-svg-icons'
import {
  faArrowLeft,
  faArrowsRotate,
  faArrowUpRightFromSquare,
  faCheck,
  faChevronDown,
  faChevronRight,
  faClock,
  faCompress,
  faCrosshairs,
  faEnvelope,
  faExpand,
  faFlask,
  faGear,
  faGlobe,
  faHeartPulse,
  faKhanda,
  faLayerGroup,
  faMagnifyingGlass,
  faMap,
  faPause,
  faPlay,
  faShieldHalved,
  faSignal,
  faTableCellsLarge,
  faUpRightFromSquare,
  faVolumeHigh,
  faVolumeXmark,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

export const icons: Record<string, IconDefinition> = {
  dashboard: faTableCellsLarge,
  map: faMap,
  activity: faHeartPulse,
  'chevron-right': faChevronRight,
  'chevron-down': faChevronDown,
  expand: faExpand,
  collapse: faCompress,
  search: faMagnifyingGlass,
  close: faXmark,
  clock: faClock,
  shield: faShieldHalved,
  swords: faKhanda,
  settings: faGear,
  volume: faVolumeHigh,
  'volume-off': faVolumeXmark,
  play: faPlay,
  pause: faPause,
  refresh: faArrowsRotate,
  'arrow-left': faArrowLeft,
  check: faCheck,
  crosshair: faCrosshairs,
  signal: faSignal,
  layers: faLayerGroup,
  flask: faFlask,
  'arrow-up-right': faArrowUpRightFromSquare,
  globe: faGlobe,
  mail: faEnvelope,
  external: faUpRightFromSquare,
  github: faGithub,
  'x-twitter': faXTwitter,
}
